version: '2'
services:
  mysql:
    image: mysql:5.5
    ports:
      - "3306:3306"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_DATABASE=employees
      - MYSQL_ROOT_PASSWORD=password
  web:
    build: ./app/
    ports:
     - "80:80"
    volumes:
     - "./app/:/app/"
