---
# Install and configure cpanm.

- name: install cpan
  apt: name={{ item }}
       state=present
  with_items:
    - cpanminus

- name: download cpanm
  get_url: url=https://cpanmin.us/
           dest=/tmp/cpanm.pl
           mode=755

- name: install cpanm so that we can use the ansible cpanm module
  command: perl cpanm.pl App::cpanminus
  args:
    chdir: /tmp/
    creates: /usr/local/bin/cpanm

#- name: add cpanm symbolic link to /usr/bin/
#  file: src=/usr/local/bin/cpanm
#        dest=/usr/bin/cpanm
#        state=link
